# Generated by Django 4.2.14 on 2024-08-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate_app", "0002_property_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
